name: unit-tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s --health-timeout=5s --health-retries=15
    strategy:
      matrix:
        app: [orders-app, customers-app]
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set DB name
        run: |
          if [ "${{ matrix.app }}" = "orders-app" ]; then echo "DB_NAME=orders_service_test" >> $GITHUB_ENV; else echo "DB_NAME=customers_service_test" >> $GITHUB_ENV; fi

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.8'
          bundler-cache: true

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Prepare DB
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/${{ env.DB_NAME }}
        run: bundle exec rails db:prepare

      - name: Run RSpec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/${{ env.DB_NAME }}
          RABBITMQ_URL: amqp://guest:guest@localhost:5672
        run: bundle exec rspec --format progress
